import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';

const indexHtml = await readFile(
  new URL('../index.html', import.meta.url),
  'utf8',
);
const customCss = await readFile(
  new URL('../assets/css/custom.css', import.meta.url),
  'utf8',
);
const gitignore = await readFile(
  new URL('../.gitignore', import.meta.url),
  'utf8',
);

function loadCodeRenderer() {
  // Docsify v5 compiles Markdown synchronously, so an `async` renderer resolves
  // into the page as the string "[object Promise]". Pin the sync signature.
  const match = indexHtml.match(
    /code:\s*(function\(token\)\s*\{[\s\S]*?\r?\n\s*\})\s*\}/,
  );

  assert.ok(match, 'Docsify code renderer must use the sync v5 token signature');

  return {
    renderCode: vm.runInNewContext(`(${match[1]})`),
  };
}

function loadMermaidRenderer(renderImpl) {
  const match = indexHtml.match(
    /(function renderMermaidDiagrams\(\) \{[\s\S]*?\r?\n {4}\})/,
  );

  assert.ok(match, 'index.html must define renderMermaidDiagrams()');

  const nodes = [];
  const renderCalls = [];
  const context = vm.createContext({
    Array,
    mermaidIndex: 0,
    console: { error() {} },
    document: {
      querySelectorAll: () =>
        nodes.filter(node => !('data-processed' in node.attributes)),
    },
    mermaid: {
      render(id, code, callback) {
        renderCalls.push({ id, code });
        renderImpl(id, code, callback);
      },
    },
  });

  vm.runInContext(match[1], context);

  return {
    renderCalls,
    addNode(text) {
      const node = {
        textContent: text,
        innerHTML: text,
        attributes: {},
        setAttribute(name, value) {
          this.attributes[name] = value;
        },
      };
      nodes.push(node);
      return node;
    },
    render: () => vm.runInContext('renderMermaidDiagrams()', context),
  };
}

test('loads the pinned Docsify v5 core assets', () => {
  assert.match(
    indexHtml,
    /https:\/\/cdn\.jsdelivr\.net\/npm\/docsify@5\.0\.0\/dist\/themes\/core\.min\.css/,
  );
  assert.match(
    indexHtml,
    /https:\/\/cdn\.jsdelivr\.net\/npm\/docsify@5\.0\.0\/dist\/docsify\.min\.js/,
  );
  assert.doesNotMatch(indexHtml, /docsify@4/);
  assert.match(
    indexHtml,
    /https:\/\/cdn\.jsdelivr\.net\/npm\/mermaid@9\.3\.0\/dist\/mermaid\.min\.js/,
  );
  assert.doesNotMatch(indexHtml, /mermaid\.min\.css/);
});

test('inline scripts are valid JavaScript', () => {
  const scripts = [...indexHtml.matchAll(/<script>([\s\S]*?)<\/script>/g)];
  assert.ok(scripts.length > 0);
  for (const [, source] of scripts) {
    assert.doesNotThrow(() => new vm.Script(source));
  }
});

test('ignores LikeC4 outputs generated by CI', () => {
  assert.match(gitignore, /^assets\/js\/\*-components\.js$/m);
  assert.match(gitignore, /^\*\/likec4\/$/m);
});

test('uses v5 defaults for optional behavior', () => {
  assert.doesNotMatch(indexHtml, /sidebar-chevron/);
  assert.doesNotMatch(indexHtml, /core-dark\.min\.css/);
  assert.doesNotMatch(indexHtml, /addons\/vue\.min\.css/);
  assert.doesNotMatch(indexHtml, /repo:/);
});

test('applies the Poort8 docs theme', () => {
  assert.match(indexHtml, /<body class="sidebar-group-underline">/);
  assert.match(
    indexHtml,
    /fonts\.googleapis\.com\/css2\?family=IBM\+Plex\+Mono[^"]*IBM\+Plex\+Sans[^"]*Poppins/,
  );
  // Fonts must load before custom.css so the theme properties can use them.
  assert.ok(
    indexHtml.indexOf('fonts.googleapis.com/css2') <
      indexHtml.indexOf('assets/css/custom.css'),
  );
  assert.match(indexHtml, /logo: 'assets\/images\/poort8-logo\.png'/);
  assert.match(indexHtml, /subMaxLevel: 2/);
  assert.match(indexHtml, /auto2top: true/);
  assert.match(indexHtml, /theme: 'base'/);
  assert.match(indexHtml, /mirrorActors: false/);
});

test('loads the search, copy-code and pagination plugins after Docsify', () => {
  const core = indexHtml.indexOf('docsify@5.0.0/dist/docsify.min.js');
  for (const plugin of [
    'docsify@5.0.0/dist/plugins/search.min.js',
    'docsify-copy-code@3',
    'docsify-pagination@2/dist/docsify-pagination.min.js',
  ]) {
    const position = indexHtml.indexOf(plugin);
    assert.ok(position > core, `${plugin} must load after docsify.min.js`);
  }
  assert.doesNotMatch(indexHtml, /docsify-tabs/);
});

test('uses Dutch plugin texts on the DVU pages', () => {
  // Plugins pick the first key found in the path, so '/dvu/' must precede '/'.
  for (const key of ['placeholder', 'noData', 'buttonText', 'successText', 'previousText', 'nextText']) {
    assert.match(
      indexHtml,
      new RegExp(`${key}: \{ '/dvu/': '[^']+', '/dvu-draft/': '[^']+', '/': '[^']+' \}`),
      `${key} must have Dutch text for /dvu/`,
    );
  }
});

test('adds an edit-on-GitHub link without a last-updated date', () => {
  assert.match(
    indexHtml,
    /'https:\/\/github\.com\/POORT8\/Poort8\.Docs\/blob\/main\/' \+ vm\.route\.file/,
  );
  assert.match(indexHtml, /class="page-meta"/);
  assert.match(indexHtml, /Bewerk deze pagina op GitHub/);
  assert.match(indexHtml, /Edit this page on GitHub/);
  assert.doesNotMatch(indexHtml, /docsify-updated|formatUpdated/);
});

function loadEditLinkHook(route) {
  const match = indexHtml.match(
    /(function\(hook, vm\) \{\s*hook\.beforeEach\([\s\S]*?\r?\n {8}\})/,
  );
  assert.ok(match, 'index.html must define the edit-link plugin');
  let beforeEach;
  vm.runInNewContext(`(${match[1]})`)(
    { beforeEach: fn => { beforeEach = fn; } },
    { route },
  );
  return beforeEach;
}

test('links each page to its source file on GitHub', () => {
  const english = loadEditLinkHook({ file: 'gds/architecture.md', path: '/gds/architecture' });
  assert.match(
    english('# Architecture'),
    /^# Architecture\n\n<div class="page-meta"><a href="https:\/\/github\.com\/POORT8\/Poort8\.Docs\/blob\/main\/gds\/architecture\.md"[^>]*>Edit this page on GitHub<\/a><\/div>$/,
  );
  const dutch = loadEditLinkHook({ file: 'dvu/faq.md', path: '/dvu/faq' });
  assert.match(dutch('# FAQ'), />Bewerk deze pagina op GitHub</);
});

test('leaves the 404 page without an edit link', () => {
  // Docsify replaces the Markdown with "# 404 - ..." and keeps the failed
  // response on the route.
  const notFound = loadEditLinkHook({
    file: 'missing.md',
    path: '/missing',
    response: { ok: false, status: 404 },
  });
  assert.equal(notFound('# 404 - File not found'), '# 404 - File not found');
  const empty = loadEditLinkHook({ file: 'missing.md', path: '/missing' });
  assert.equal(empty(null), null);
});

test('serves the dataspace-themed 404 page', async () => {
  assert.match(indexHtml, /notFoundPage: true/);
  const page = await readFile(new URL('../_404.md', import.meta.url), 'utf8');
  assert.match(page, /^# /m);
  assert.match(page, /```mermaid\r?\nsequenceDiagram/);
});

test('highlights every code language the docs use', () => {
  const core = indexHtml.indexOf('docsify@5.0.0/dist/docsify.min.js');
  for (const lang of ['json', 'http', 'bash', 'csharp', 'yaml', 'python']) {
    const position = indexHtml.indexOf(
      `https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-${lang}.min.js`,
    );
    assert.ok(position > core, `prism-${lang} must load after docsify.min.js`);
  }
});

test('gives Mermaid edge labels a plain background', () => {
  assert.match(indexHtml, /edgeLabelBackground: '#ffffff'/);
});

test('keeps theme overrides ahead of core and plugin rules', () => {
  // Core clears the pill background on a page link without sub-headings
  // (`.active > a.page-link:only-child`), so the pill needs that case too.
  assert.match(customCss, /\.sidebar \.sidebar-nav li\.active > a\.page-link:only-child/);
  // #0a7fb3 on white is 4.47:1, below WCAG AA for text; links use a darker tint.
  assert.match(customCss, /--link-color\s*:\s*#0976a8;/);
  assert.match(customCss, /\.docsify-pagination-container/);
  assert.match(customCss, /\.docsify-copy-code-button/);
});

test('links section landing pages by their route, not README.md', async () => {
  // `README.md` resolves to #/<section>/README, while the menu and home page
  // link to #/<section>/. Docsify only marks the sidebar item active (and
  // pagination only finds the page) when the two match.
  const { readdir } = await import('node:fs/promises');
  const root = new URL('../', import.meta.url);
  const entries = await readdir(root, { withFileTypes: true });
  for (const entry of entries.filter(e => e.isDirectory())) {
    const sidebar = await readFile(new URL(`${entry.name}/_sidebar.md`, root), 'utf8').catch(() => null);
    if (!sidebar) {
      continue;
    }
    assert.doesNotMatch(sidebar, /\]\((\.\/)?README\.md\)/, `${entry.name}/_sidebar.md links to README.md`);
  }
});

test('preserves required navigation behavior', () => {
  assert.match(indexHtml, /name: 'Poort8 Docs'/);
  assert.match(indexHtml, /loadSidebar: true/);
  assert.match(indexHtml, /relativePath: true/);
  assert.match(
    indexHtml,
    /if \(!document\.querySelector\('likec4-view'\)\) return;/,
  );
});

test('renders Mermaid and LikeC4 tokens with the Docsify v5 API', () => {
  const { renderCode } = loadCodeRenderer();
  const context = {
    origin: {
      code: token => `fallback:${token.text}`,
    },
  };

  // Mermaid source is emitted escaped and rendered later, from a placeholder.
  assert.equal(
    renderCode.call(context, { text: 'flowchart LR; A-->B', lang: 'mermaid' }),
    '<div class="mermaid-diagram"><div class="diagram-actions">' +
      '<button type="button" class="diagram-expand diagram-source" aria-expanded="false">&lt;/&gt; Source</button>' +
      '<button type="button" class="diagram-expand" aria-label="Open diagram in larger view"><span class="diagram-expand__icon" aria-hidden="true">&#10530;</span>Expand</button>' +
      '</div><pre class="mermaid">flowchart LR; A--&gt;B</pre>' +
      '<pre class="mermaid-source" data-lang="mermaid" hidden><code class="lang-mermaid">flowchart LR; A--&gt;B</code></pre></div>',
  );
  assert.equal(
    renderCode.call(context, {
      text: '// view: overview\nview overview {}',
      lang: 'likec4',
    }),
    '<likec4-view class="likec4-embed" view-id="overview" dynamic-variant="sequence"></likec4-view>',
  );
  assert.equal(
    renderCode.call(context, { text: 'const answer = 42;', lang: 'js' }),
    'fallback:const answer = 42;',
  );
});

test('sizes LikeC4 embeds to the rendered diagram', () => {
  // A fixed embed height letterboxes wide diagrams, so the height is derived
  // from the rendered diagram and refreshed when the container width changes.
  assert.match(indexHtml, /function measureRenderedDiagram\(viewport\)/);
  assert.match(indexHtml, /function fitLikeC4Embeds\(force\)/);
  assert.match(
    indexHtml,
    /\.react-flow__node, \.react-flow__edge, \.react-flow__edgelabel-renderer > \*/,
  );
  assert.match(indexHtml, /host\.style\.height = target \+ 'px';/);
  assert.match(
    indexHtml,
    /window\.addEventListener\('resize', function\(\) \{/,
  );
  assert.doesNotMatch(indexHtml, /min-height:\s*720px/);
});

test('provides a Mermaid pop-out that fills the dialog', () => {
  assert.match(indexHtml, /function installMermaidPopOuts\(\)/);
  assert.match(indexHtml, /dialog\.showModal\(\)/);
  // The Source button shares the .diagram-expand style but must not open the pop-out.
  assert.match(indexHtml, /querySelector\('\.diagram-expand:not\(\.diagram-source\)'\)/);
  assert.match(indexHtml, /srcPre\.hidden = !srcPre\.hidden;/);
  assert.match(indexHtml, /className = 'diagram-popout'/);
  // The pop-out copy must scale with the dialog instead of keeping Mermaid's
  // inline max-width, and the button must sit on the diagram, not above it.
  assert.match(indexHtml, /function prepareDiagramSvg\(svg\)/);
  assert.match(indexHtml, /\.diagram-expand \{[^}]*position: absolute;/);
});

test('strips Mermaid sizing hints from the pop-out copy', () => {
  const match = indexHtml.match(
    /(function prepareDiagramSvg\(svg\) \{[\s\S]*?\r?\n {4}\})/,
  );

  assert.ok(match, 'index.html must define prepareDiagramSvg()');

  const clone = {
    attributes: { width: '100%', height: '640' },
    styles: { 'max-width': '1155px' },
    style: {
      removeProperty(name) {
        delete clone.styles[name];
      },
    },
    removeAttribute(name) {
      delete clone.attributes[name];
    },
    getAttribute(name) {
      return clone.attributes[name] ?? null;
    },
    setAttribute(name, value) {
      clone.attributes[name] = value;
    },
  };
  const prepare = vm.runInNewContext(`(${match[1]})`);
  const result = prepare({ cloneNode: () => clone });

  assert.equal(result, clone);
  assert.deepEqual(clone.styles, {});
  assert.equal(clone.attributes.width, undefined);
  assert.equal(clone.attributes.height, undefined);
  assert.equal(clone.attributes.preserveAspectRatio, 'xMidYMid meet');
});

test('renders every Mermaid placeholder with a unique id', () => {
  const renderer = loadMermaidRenderer((id, code, callback) => {
    callback(`<svg id="${id}">${code}</svg>`);
  });
  const first = renderer.addNode('flowchart LR; A-->B');
  const second = renderer.addNode('flowchart LR; C-->D');

  renderer.render();

  // Mermaid's renderers look their SVG up with a document-wide id selector, so
  // reused ids leave every diagram but the first without a viewBox (blank).
  assert.deepEqual(
    renderer.renderCalls.map(call => call.id),
    ['mermaid-svg-0', 'mermaid-svg-1'],
  );
  assert.deepEqual(
    renderer.renderCalls.map(call => call.code),
    ['flowchart LR; A-->B', 'flowchart LR; C-->D'],
  );
  assert.equal(first.innerHTML, '<svg id="mermaid-svg-0">flowchart LR; A-->B</svg>');
  assert.equal(second.innerHTML, '<svg id="mermaid-svg-1">flowchart LR; C-->D</svg>');
  assert.equal(first.attributes['data-processed'], 'true');

  // Re-running after a route change must not re-render or reuse ids.
  const third = renderer.addNode('flowchart LR; E-->F');
  renderer.render();
  assert.deepEqual(
    renderer.renderCalls.map(call => call.id),
    ['mermaid-svg-0', 'mermaid-svg-1', 'mermaid-svg-2'],
  );
  assert.equal(third.innerHTML, '<svg id="mermaid-svg-2">flowchart LR; E-->F</svg>');
});

test('keeps a failing Mermaid diagram from aborting the doneEach hook', () => {
  const renderer = loadMermaidRenderer((id, code, callback) => {
    if (code.includes('boom')) {
      throw new Error('parse error');
    }
    callback(`<svg id="${id}">${code}</svg>`);
  });
  renderer.addNode('boom');
  const good = renderer.addNode('flowchart LR; A-->B');

  renderer.render();

  assert.equal(good.innerHTML, '<svg id="mermaid-svg-1">flowchart LR; A-->B</svg>');
});

test('renders Mermaid and loads LikeC4 bundles after each page load', () => {
  const doneEach = indexHtml.match(
    /hook\.doneEach\(function\(\) \{([\s\S]*?)\r?\n {10}\}\);/,
  );

  assert.ok(doneEach, 'plugin must register a doneEach hook');
  assert.match(doneEach[1], /renderMermaidDiagrams\(\);/);
  assert.match(doneEach[1], /installMermaidPopOuts\(\);/);
  assert.match(doneEach[1], /loadBundleForRoute\(window\.location\.hash \|\| '\/'\);/);
  assert.match(doneEach[1], /applyLikeC4OverlayFix\(\);/);
  assert.match(doneEach[1], /fitLikeC4Embeds\(true\);/);
});
