import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';

const indexHtml = await readFile(
  new URL('../index.html', import.meta.url),
  'utf8',
);
const gitignore = await readFile(
  new URL('../.gitignore', import.meta.url),
  'utf8',
);

function loadCodeRenderer() {
  // Docsify v5 compiles Markdown synchronously, so an `async` renderer resolves
  // into the page as the string "[object Promise]". Pin the sync signature.
  const match = indexHtml.match(
    /code:\s*(function\(token\)\s*\{[\s\S]*?\r?\n\s*\})\s*\}/,
  );

  assert.ok(match, 'Docsify code renderer must use the sync v5 token signature');

  return {
    renderCode: vm.runInNewContext(`(${match[1]})`),
  };
}

function loadMermaidRenderer(renderImpl) {
  const match = indexHtml.match(
    /(function renderMermaidDiagrams\(\) \{[\s\S]*?\r?\n {4}\})/,
  );

  assert.ok(match, 'index.html must define renderMermaidDiagrams()');

  const nodes = [];
  const renderCalls = [];
  const context = vm.createContext({
    Array,
    mermaidIndex: 0,
    console: { error() {} },
    document: {
      querySelectorAll: () =>
        nodes.filter(node => !('data-processed' in node.attributes)),
    },
    mermaid: {
      render(id, code, callback) {
        renderCalls.push({ id, code });
        renderImpl(id, code, callback);
      },
    },
  });

  vm.runInContext(match[1], context);

  return {
    renderCalls,
    addNode(text) {
      const node = {
        textContent: text,
        innerHTML: text,
        attributes: {},
        setAttribute(name, value) {
          this.attributes[name] = value;
        },
      };
      nodes.push(node);
      return node;
    },
    render: () => vm.runInContext('renderMermaidDiagrams()', context),
  };
}

test('loads the pinned Docsify v5 core assets', () => {
  assert.match(
    indexHtml,
    /https:\/\/cdn\.jsdelivr\.net\/npm\/docsify@5\.0\.0\/dist\/themes\/core\.min\.css/,
  );
  assert.match(
    indexHtml,
    /https:\/\/cdn\.jsdelivr\.net\/npm\/docsify@5\.0\.0\/dist\/docsify\.min\.js/,
  );
  assert.doesNotMatch(indexHtml, /docsify@4/);
  assert.match(
    indexHtml,
    /https:\/\/cdn\.jsdelivr\.net\/npm\/mermaid@9\.3\.0\/dist\/mermaid\.min\.js/,
  );
  assert.doesNotMatch(indexHtml, /mermaid\.min\.css/);
});

test('ignores LikeC4 outputs generated by CI', () => {
  assert.match(gitignore, /^assets\/js\/\*-components\.js$/m);
  assert.match(gitignore, /^\*\/likec4\/$/m);
});

test('uses v5 defaults for optional behavior', () => {
  assert.match(indexHtml, /<body>/);
  assert.doesNotMatch(indexHtml, /sidebar-chevron/);
  assert.doesNotMatch(indexHtml, /core-dark\.min\.css/);
  assert.doesNotMatch(indexHtml, /addons\/vue\.min\.css/);
  assert.doesNotMatch(indexHtml, /\bauto2top:/);
  assert.doesNotMatch(indexHtml, /\bsubMaxLevel:/);
  assert.doesNotMatch(indexHtml, /\brepo:/);
});

test('preserves required navigation behavior', () => {
  assert.match(indexHtml, /name: 'Poort8 Docs'/);
  assert.match(indexHtml, /loadSidebar: true/);
  assert.match(indexHtml, /relativePath: true/);
  assert.match(
    indexHtml,
    /if \(!document\.querySelector\('likec4-view'\)\) return;/,
  );
});

test('renders Mermaid and LikeC4 tokens with the Docsify v5 API', () => {
  const { renderCode } = loadCodeRenderer();
  const context = {
    origin: {
      code: token => `fallback:${token.text}`,
    },
  };

  // Mermaid source is emitted escaped and rendered later, from a placeholder.
  assert.equal(
    renderCode.call(context, { text: 'flowchart LR; A-->B', lang: 'mermaid' }),
    '<div class="mermaid-diagram"><button type="button" class="diagram-expand" aria-label="Open diagram in larger view"><span class="diagram-expand__icon" aria-hidden="true">&#10530;</span>Expand</button><pre class="mermaid">flowchart LR; A--&gt;B</pre></div>',
  );
  assert.equal(
    renderCode.call(context, {
      text: '// view: overview\nview overview {}',
      lang: 'likec4',
    }),
    '<likec4-view class="likec4-embed" view-id="overview" dynamic-variant="sequence"></likec4-view>',
  );
  assert.equal(
    renderCode.call(context, { text: 'const answer = 42;', lang: 'js' }),
    'fallback:const answer = 42;',
  );
});

test('sizes LikeC4 embeds to the rendered diagram', () => {
  // A fixed embed height letterboxes wide diagrams, so the height is derived
  // from the rendered diagram and refreshed when the container width changes.
  assert.match(indexHtml, /function measureRenderedDiagram\(viewport\)/);
  assert.match(indexHtml, /function fitLikeC4Embeds\(force\)/);
  assert.match(
    indexHtml,
    /\.react-flow__node, \.react-flow__edge, \.react-flow__edgelabel-renderer > \*/,
  );
  assert.match(indexHtml, /host\.style\.height = target \+ 'px';/);
  assert.match(
    indexHtml,
    /window\.addEventListener\('resize', function\(\) \{/,
  );
  assert.doesNotMatch(indexHtml, /min-height:\s*720px/);
});

test('provides a Mermaid pop-out that fills the dialog', () => {
  assert.match(indexHtml, /function installMermaidPopOuts\(\)/);
  assert.match(indexHtml, /dialog\.showModal\(\)/);
  assert.match(indexHtml, /className = 'diagram-popout'/);
  // The pop-out copy must scale with the dialog instead of keeping Mermaid's
  // inline max-width, and the button must sit on the diagram, not above it.
  assert.match(indexHtml, /function prepareDiagramSvg\(svg\)/);
  assert.match(indexHtml, /\.diagram-expand \{[^}]*position: absolute;/);
});

test('strips Mermaid sizing hints from the pop-out copy', () => {
  const match = indexHtml.match(
    /(function prepareDiagramSvg\(svg\) \{[\s\S]*?\r?\n {4}\})/,
  );

  assert.ok(match, 'index.html must define prepareDiagramSvg()');

  const clone = {
    attributes: { width: '100%', height: '640' },
    styles: { 'max-width': '1155px' },
    style: {
      removeProperty(name) {
        delete clone.styles[name];
      },
    },
    removeAttribute(name) {
      delete clone.attributes[name];
    },
    getAttribute(name) {
      return clone.attributes[name] ?? null;
    },
    setAttribute(name, value) {
      clone.attributes[name] = value;
    },
  };
  const prepare = vm.runInNewContext(`(${match[1]})`);
  const result = prepare({ cloneNode: () => clone });

  assert.equal(result, clone);
  assert.deepEqual(clone.styles, {});
  assert.equal(clone.attributes.width, undefined);
  assert.equal(clone.attributes.height, undefined);
  assert.equal(clone.attributes.preserveAspectRatio, 'xMidYMid meet');
});

test('renders every Mermaid placeholder with a unique id', () => {
  const renderer = loadMermaidRenderer((id, code, callback) => {
    callback(`<svg id="${id}">${code}</svg>`);
  });
  const first = renderer.addNode('flowchart LR; A-->B');
  const second = renderer.addNode('flowchart LR; C-->D');

  renderer.render();

  // Mermaid's renderers look their SVG up with a document-wide id selector, so
  // reused ids leave every diagram but the first without a viewBox (blank).
  assert.deepEqual(
    renderer.renderCalls.map(call => call.id),
    ['mermaid-svg-0', 'mermaid-svg-1'],
  );
  assert.deepEqual(
    renderer.renderCalls.map(call => call.code),
    ['flowchart LR; A-->B', 'flowchart LR; C-->D'],
  );
  assert.equal(first.innerHTML, '<svg id="mermaid-svg-0">flowchart LR; A-->B</svg>');
  assert.equal(second.innerHTML, '<svg id="mermaid-svg-1">flowchart LR; C-->D</svg>');
  assert.equal(first.attributes['data-processed'], 'true');

  // Re-running after a route change must not re-render or reuse ids.
  const third = renderer.addNode('flowchart LR; E-->F');
  renderer.render();
  assert.deepEqual(
    renderer.renderCalls.map(call => call.id),
    ['mermaid-svg-0', 'mermaid-svg-1', 'mermaid-svg-2'],
  );
  assert.equal(third.innerHTML, '<svg id="mermaid-svg-2">flowchart LR; E-->F</svg>');
});

test('keeps a failing Mermaid diagram from aborting the doneEach hook', () => {
  const renderer = loadMermaidRenderer((id, code, callback) => {
    if (code.includes('boom')) {
      throw new Error('parse error');
    }
    callback(`<svg id="${id}">${code}</svg>`);
  });
  renderer.addNode('boom');
  const good = renderer.addNode('flowchart LR; A-->B');

  renderer.render();

  assert.equal(good.innerHTML, '<svg id="mermaid-svg-1">flowchart LR; A-->B</svg>');
});

test('renders Mermaid and loads LikeC4 bundles after each page load', () => {
  const doneEach = indexHtml.match(
    /hook\.doneEach\(function\(\) \{([\s\S]*?)\r?\n {10}\}\);/,
  );

  assert.ok(doneEach, 'plugin must register a doneEach hook');
  assert.match(doneEach[1], /renderMermaidDiagrams\(\);/);
  assert.match(doneEach[1], /installMermaidPopOuts\(\);/);
  assert.match(doneEach[1], /loadBundleForRoute\(window\.location\.hash \|\| '\/'\);/);
  assert.match(doneEach[1], /applyLikeC4OverlayFix\(\);/);
  assert.match(doneEach[1], /fitLikeC4Embeds\(true\);/);
});
