markdown: kramdown
theme: minima
baseurl: ""
url: "https://docs.poort8.nl"

navigation:
  - title: "Home"
    url: "/"
  - title: "HeyWim"
    url: "/HeyWim"
  - title: "NoodleBar"
    url: "/NoodleBar"
  - title: "Keyper"
    url: "/Keyper"
  - title: "DVU"
    url: "/DVU.md"

plugins: []

minima:
  sidebar:
    - navigation

sass:
  style: compressed

title: "Poort8 Docs"
url: "https://docs.poort8.nl"
plugins: []

header_pages:
  - index.md
  - guide.md
