markdown: kramdown
theme: minima
baseurl: ""
url: "https://docs.poort8.nl"

title: "Poort8 Docs"
description: "Documentation portal for Poort8 products"

# Navigation structure
navigation:
  - title: "Home"
    url: "/"
  - title: "HeyWim"
    url: "/heywim"
  - title: "NoodleBar"
    url: "/noodlebar"
  - title: "Keyper"
    url: "/keyper"
  - title: "DVU"
    url: "/dvu"

plugins:
  - jekyll-github-metadata
  - jekyll-redirect-from

minima:
  sidebar:
    - navigation

sass:
  style: compressed

# Pages to include in header navigation
header_pages:
  - index.md
  - guide.md
