# Development configuration for Jekyll

# Disable unnecessary plugins during development
plugins:
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-navigation

# Overrides for development
url: "http://localhost:4001"
theme: null
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Set environment to development
JEKYLL_ENV: development
