name: CI
on: [pull_request]

jobs:
  # Jekyll build (existing)
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with: { ruby-version: '3.3.8' }
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec jekyll build --source docs --trace
      - run: bundle exec htmlproofer ./_site --disable-external

  # Pre-deployment quality checks
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      # Test 1: Link Checking (ignores internal Docsify routes)
      - name: Check Markdown Links 🔗
        run: |
          echo "Installing markdown-link-check..."
          npm install -g markdown-link-check
          
          echo "Checking Docsify markdown files only..."
          # Find markdown files excluding docs/ and docs-agents/ folders
          # Use -exec to handle filenames with spaces properly
          find . -name "*.md" \
            -not -path "./docs/*" \
            -not -path "./docs-agents/*" \
            -not -path "./node_modules/*" \
            -not -path "./.git/*" \
            -exec markdown-link-check {} \;

      # Test 2: HTML Validation
      - name: Validate HTML Files ✅
        run: |
          echo "Validating HTML files..."
          
          # Basic HTML structure check for index.html
          if grep -q "<!DOCTYPE html>" index.html && grep -q "<html" index.html && grep -q "</html>" index.html; then
            echo "✅ index.html has valid HTML structure"
          else
            echo "❌ index.html missing required HTML structure"
            exit 1
          fi
          
          # Check for required meta tags
          if grep -q 'charset="UTF-8"' index.html && grep -q 'name="viewport"' index.html; then
            echo "✅ index.html has required meta tags"
          else
            echo "❌ index.html missing required meta tags"
            exit 1
          fi
          
          # Check 404.html if it exists
          if [ -f "404.html" ]; then
            if grep -q "<!DOCTYPE html>" 404.html && grep -q "<html" 404.html && grep -q "</html>" 404.html; then
              echo "✅ 404.html has valid HTML structure"
            else
              echo "❌ 404.html missing required HTML structure"
              exit 1
            fi
          else
            echo "⚠️  404.html not found (optional)"
          fi
