name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with: { ruby-version: '3.3.0' }
      - run: bundle install --jobs 4 --retry 3
      - run: JEKYLL_ENV=development bundle exec jekyll build --incremental --trace
      - run: bundle exec htmlproofer ./_site --disable-external
