name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with: { ruby-version: '3.3.8' }
      - run: bundle install --jobs 4 --retry 3
      - run: JEKYLL_ENV=production bundle exec jekyll build --source docs --trace
      - run: bundle exec htmlproofer ./_site --disable-external
